/* eslint-disable @typescript-eslint/no-explicit-any */
import { promises as fs } from "fs";
import path from "path";
import os from "os";
import type { ProjectContext } from "../analyzers/project-analyzer";
import { readJsonSafe, ensureDir } from "../utils/file-utils";

interface MCPRegistryEntry {
  command: string;
  args: string[];
  description: string;
  requiredEnv: string[];
  recommended: boolean;
  tags: string[];
  priority: string;
}

interface SetupAnswers {
  installType: "local" | "global" | "both";
  verbosity: "verbose" | "balanced" | "compressed";
  enableSkills: string[];
  enableMCPs: string[];
}

export class ConfigurationGenerator {
  private mcpRegistry: Record<string, MCPRegistryEntry> | null = null;

  /**
   * Generate local .claude/ configuration for project
   */
  async generateLocal(
    projectRoot: string,
    projectContext: ProjectContext,
    answers: SetupAnswers,
  ): Promise<void> {
    const claudeDir = path.join(projectRoot, ".claude");

    // Create .claude directory structure
    await this.createDirectoryStructure(claudeDir);

    // Generate CLAUDE.md
    await this.generateClaudeMd(claudeDir, projectContext, answers);

    // Generate settings.json
    await this.generateSettings(claudeDir, projectContext, answers);

    // Generate .mcp.json
    await this.generateMcpConfig(claudeDir, answers);

    // Generate .gitignore entry
    await this.updateGitignore(projectRoot);
  }

  /**
   * Generate global ~/.claude/ configuration
   */
  async generateGlobal(
    projectContext: ProjectContext,
    answers: SetupAnswers,
  ): Promise<void> {
    const claudeDir = path.join(os.homedir(), ".claude");

    // Create .claude directory structure
    await this.createDirectoryStructure(claudeDir);

    // Generate CLAUDE.md (global template)
    await this.generateGlobalClaudeMd(claudeDir);

    // Generate settings.json
    await this.generateSettings(claudeDir, projectContext, answers);

    // Generate .mcp.json
    await this.generateMcpConfig(claudeDir, answers);
  }

  /**
   * Create .claude/ directory structure
   */
  private async createDirectoryStructure(claudeDir: string): Promise<void> {
    const dirs = [
      claudeDir,
      path.join(claudeDir, "skills"),
      path.join(claudeDir, "commands"),
      path.join(claudeDir, "agents"),
    ];

    for (const dir of dirs) {
      await ensureDir(dir);
    }
  }

  private async generateClaudeMd(
    claudeDir: string,
    projectContext: ProjectContext,
    answers: SetupAnswers,
  ): Promise<void> {
    const content = `# ${path.basename(path.dirname(claudeDir))} - Project Context

## Project Information

**Type**: ${projectContext.type}
**Tech Stack**: ${projectContext.techStack.join(", ")}
${projectContext.domain.length > 0 ? `**Domain**: ${projectContext.domain.join(", ")}` : ""}
${projectContext.gitWorkflow ? `**Git Workflow**: ${projectContext.gitWorkflow}` : ""}

## Purpose

${projectContext.purpose || "Add project purpose and description here"}

## Development Guidelines

### Code Style
- Follow existing patterns in the codebase
- Maintain consistent naming conventions
- Write tests for new features

### Git Workflow
${this.generateGitWorkflowInstructions(projectContext)}

### Skills Enabled
${answers.enableSkills.map((s) => `- ${s}`).join("\n")}

### MCP Servers Enabled
${answers.enableMCPs.map((m) => `- ${m}`).join("\n")}

## Custom Instructions

Add project-specific instructions here for Claude Code to follow.

---

*Generated by code-assistant-claude v0.1.0*
`;

    await fs.writeFile(path.join(claudeDir, "CLAUDE.md"), content, "utf-8");
  }

  private async generateGlobalClaudeMd(claudeDir: string): Promise<void> {
    const content = `# Global Claude Code Configuration

## General Development Guidelines

### Code Quality
- Write clean, maintainable code
- Follow SOLID principles
- Add comments for complex logic
- Write comprehensive tests

### Security
- Never commit secrets or credentials
- Follow security best practices
- Validate all user inputs

### Performance
- Optimize for readability first
- Profile before optimizing
- Consider scalability

## Global Skills

Skills enabled globally apply to all projects unless overridden locally.

## Global MCP Servers

MCP servers enabled globally provide consistent capabilities across projects.

---

*Generated by code-assistant-claude v0.1.0*
`;

    await fs.writeFile(path.join(claudeDir, "CLAUDE.md"), content, "utf-8");
  }

  private async generateSettings(
    claudeDir: string,
    projectContext: ProjectContext,
    answers: SetupAnswers,
  ): Promise<void> {
    const settings = {
      version: "1.0.0",
      verbosity: answers.verbosity,
      tokenBudget: {
        total: 200000,
        reserved: 10000,
        system: 10000,
        dynamic: 30000,
        working: 150000,
      },
      skills: {
        enabled: answers.enableSkills,
        autoActivate: ["code-reviewer"],
      },
      mcps: {
        enabled: answers.enableMCPs,
      },
      project: {
        type: projectContext.type,
        techStack: projectContext.techStack,
        domain: projectContext.domain,
        gitWorkflow: projectContext.gitWorkflow,
      },
    };

    await fs.writeFile(
      path.join(claudeDir, "settings.json"),
      JSON.stringify(settings, null, 2),
      "utf-8",
    );
  }

  /**
   * Generate .mcp.json configuration file
   */
  private async generateMcpConfig(
    claudeDir: string,
    answers: SetupAnswers,
  ): Promise<void> {
    const mcpServers: Record<string, unknown> = {};

    // Load MCP registry
    await this.loadMcpRegistry();

    // Add enabled MCPs with configuration from registry
    for (const mcpName of answers.enableMCPs) {
      const config = await this.getMcpConfig(mcpName);
      mcpServers[mcpName] = config;
    }

    const config = {
      mcpServers,
    };

    await fs.writeFile(
      path.join(claudeDir, ".mcp.json"),
      JSON.stringify(config, null, 2),
      "utf-8",
    );
  }

  /**
   * Load MCP registry from external JSON file
   */
  private async loadMcpRegistry(): Promise<void> {
    if (this.mcpRegistry) return; // Already loaded

    const registryPath = path.join(__dirname, "mcp-registry.json");
    this.mcpRegistry =
      await readJsonSafe<Record<string, MCPRegistryEntry>>(registryPath);

    if (!this.mcpRegistry) {
      console.warn("Could not load MCP registry, using defaults");
      this.mcpRegistry = {};
    }
  }

  /**
   * Get MCP configuration from registry
   */
  private async getMcpConfig(mcpName: string): Promise<unknown> {
    await this.loadMcpRegistry();

    const entry = this.mcpRegistry?.[mcpName];

    if (entry) {
      const config: any = {
        command: entry.command,
        args: entry.args,
      };

      // Add environment variables if required
      if (entry.requiredEnv && entry.requiredEnv.length > 0) {
        config.env = {};
        for (const envVar of entry.requiredEnv) {
          config.env[envVar] =
            process.env[envVar] || `your-${envVar.toLowerCase()}-here`;
        }
      }

      return config;
    }

    // Fallback for unknown MCP
    return {
      command: "npx",
      args: ["-y", `mcp-server-${mcpName}`],
    };
  }

  private generateGitWorkflowInstructions(
    projectContext: ProjectContext,
  ): string {
    switch (projectContext.gitWorkflow) {
      case "gitflow":
        return `Using **GitFlow**:
- Feature branches: \`feature/*\`
- Release branches: \`release/*\`
- Hotfix branches: \`hotfix/*\`
- Main branch: \`main\`
- Development branch: \`develop\``;

      case "github-flow":
        return `Using **GitHub Flow**:
- Create feature branches from \`main\`
- Submit pull requests for review
- Merge to \`main\` after approval`;

      case "trunk-based":
        return `Using **Trunk-Based Development**:
- Work directly on \`main\` or very short-lived branches
- Commit frequently
- Use feature flags for incomplete features`;

      default:
        return "Follow existing Git workflow conventions in this project.";
    }
  }

  private async updateGitignore(projectRoot: string): Promise<void> {
    const gitignorePath = path.join(projectRoot, ".gitignore");

    try {
      let content = "";

      try {
        content = await fs.readFile(gitignorePath, "utf-8");
      } catch {
        // .gitignore doesn't exist, create it
      }

      // Check if .claude is already in .gitignore
      if (!content.includes(".claude")) {
        content +=
          "\n# Code Assistant Claude\n.claude/settings.local.json\n.claude/.mcp.local.json\n";
        await fs.writeFile(gitignorePath, content, "utf-8");
      }
    } catch (error) {
      // Ignore gitignore errors
      console.warn("Could not update .gitignore:", error);
    }
  }
}
